-- Align legacy US2A labels with the supplier workbook once. The WHERE clause
-- intentionally limits this to labels previously generated by the seed, so a
-- genuinely custom admin label is not overwritten.
UPDATE "CatalogArticle"
SET
  "name" = CASE "articleNumber"
    WHEN 'US2A100' THEN 'Lower Cabinet with 3 Drawers 100 cm'
    WHEN 'US2A30' THEN 'Lower Cabinet with 3 Drawers 30 cm'
    WHEN 'US2A40' THEN 'Lower Cabinet with 3 Drawers 40 cm'
    WHEN 'US2A45' THEN 'Lower Cabinet with 3 Drawers 45 cm'
    WHEN 'US2A50' THEN 'Lower Cabinet with 3 Drawers 50 cm'
    WHEN 'US2A60' THEN 'Lower Cabinet with 3 Drawers 60 cm'
    WHEN 'US2A80' THEN 'Lower Cabinet with 3 Drawers 80 cm'
    WHEN 'US2A90' THEN 'Lower Cabinet with 3 Drawers 90 cm'
  END,
  "nameDe" = CASE "articleNumber"
    WHEN 'US2A100' THEN 'Unterschrank mit Schublade/Auszug 100'
    WHEN 'US2A30' THEN 'Unterschrank mit Schublade/Auszug 30'
    WHEN 'US2A40' THEN 'Unterschrank mit Schublade/Auszug 40'
    WHEN 'US2A45' THEN 'Unterschrank mit Schublade/Auszug 45'
    WHEN 'US2A50' THEN 'Unterschrank mit Schublade/Auszug 50'
    WHEN 'US2A60' THEN 'Unterschrank mit Schublade/Auszug 60'
    WHEN 'US2A80' THEN 'Unterschrank mit Schublade/Auszug 80'
    WHEN 'US2A90' THEN 'Unterschrank mit Schublade/Auszug 90'
  END
WHERE "articleNumber" IN ('US2A100', 'US2A30', 'US2A40', 'US2A45', 'US2A50', 'US2A60', 'US2A80', 'US2A90')
  AND (
    "name" LIKE 'Lower Cabinet with Drawer/Soft-close %'
    OR "name" IN ('Base cabinet with drawers 60', 'Base cabinet with drawers 60 cm')
  );
